apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: microservices-order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /orders
            port: 3002
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /orders
            port: 3002
          initialDelaySeconds: 5