apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: microservices-product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /products
            port: 3001
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /products
            port: 3001
          initialDelaySeconds: 5